FROM splessons/base:16.04
LABEL maintainer="splessons"

RUN apt-get install -y gnustep
RUN apt-get install -y gnustep-devel
RUN apt-get install -y gobjc
RUN apt-get install -y gobjc++
RUN rm -rf /var/lib/apt/lists/*